### ISSUE TITLE
建议用docker可以忽略node环境需求

### ISSUE THREAD

**Issue by tokyo2006** [Sneezry/OpenHappyHackingCalendar#2]
这样只需要跑docker就好了 😄 
`docker run --rm -v "$PWD":/usr/src/app -w /usr/src/app node:10 /bin/bash build.sh`

**Comment by Sneezry** [comment]
其实用GitHub Actions比较简单😁

**Comment by dmwin72015** [comment]
有点慢
搞错了，是没走代理，访问不到wiki，用了个别的库走代理好使了
