### ISSUE TITLE
Could not use "nc", falling back to slower node.js method for sync requests.

### ISSUE THREAD

**Issue by Fantasia1999** [Sneezry/OpenHappyHackingCalendar#3]
Windows下`build.cmd`后提示这个该怎么解决？

**Comment by Sneezry** [comment]
不需要解决。支持nc的情况下会调用系统原生的方法做爬虫拉取Wikipedia上的内容，不支持的话就用Node的方法。Node的方法抓取Wikipedia只是速度有点慢，但并不会导致build失败。

**Comment by LeetaoGoooo** [comment]
我一build的就是大半天~~

**Comment by Sneezry** [comment]
那么你的网络可以正常访问维基百科吗？

**Comment by Sneezry** [comment]
> 我一build的就是大半天~~

那么你的网络可以正常访问维基百科吗？

**Comment by LeetaoGoooo** [comment]
> @LeeTao 那么你的网络可以正常访问维基百科吗？

是不是要开全局代理？

**Comment by Sneezry** [comment]
> > @LeeTao 那么你的网络可以正常访问维基百科吗？
> 
> 是不是要开全局代理？

至少要让Node能访问到维基百科

**Comment by Fantasia1999** [comment]
> 不需要解决。支持nc的情况下会调用系统原生的方法做爬虫拉取Wikipedia上的内容，不支持的话就用Node的方法。Node的方法抓取Wikipedia只是速度有点慢，但并不会导致build失败。

当我安装好 nc 之后，运行 build.cmd 后，总是输出一个C，这个是正常的吗？最后build成功后，会有提示吗？

**Comment by Sneezry** [comment]
> > 不需要解决。支持nc的情况下会调用系统原生的方法做爬虫拉取Wikipedia上的内容，不支持的话就用Node的方法。Node的方法抓取Wikipedia只是速度有点慢，但并不会导致build失败。
> 
> 当我安装好 nc 之后，运行 build.cmd 后，总是输出一个C，这个是正常的吗？最后build成功后，会有提示吗？

并不需要专门安装nc，我自己这边也没有nc，整个build过程不到两分钟。只输出C是因为Node卡在了拉取C语言的维基百科内容上，这应该是网络问题。

**Comment by Fantasia1999** [comment]
> > > 不需要解决。支持nc的情况下会调用系统原生的方法做爬虫拉取Wikipedia上的内容，不支持的话就用Node的方法。Node的方法抓取Wikipedia只是速度有点慢，但并不会导致build失败。
> > 
> > 
> > 当我安装好 nc 之后，运行 build.cmd 后，总是输出一个C，这个是正常的吗？最后build成功后，会有提示吗？
> 
> 并不需要专门安装nc，我自己这边也没有nc，整个build过程不到两分钟。只输出C是因为Node卡在了拉取C语言的维基百科内容上，这应该是网络问题。

那我明白了，我去解决下网络的问题，谢谢您！

**Comment by Fantasia1999** [comment]
> > > 不需要解决。支持nc的情况下会调用系统原生的方法做爬虫拉取Wikipedia上的内容，不支持的话就用Node的方法。Node的方法抓取Wikipedia只是速度有点慢，但并不会导致build失败。
> > 
> > 
> > 当我安装好 nc 之后，运行 build.cmd 后，总是输出一个C，这个是正常的吗？最后build成功后，会有提示吗？
> 
> 并不需要专门安装nc，我自己这边也没有nc，整个build过程不到两分钟。只输出C是因为Node卡在了拉取C语言的维基百科内容上，这应该是网络问题。

确实是网络的问题，现在解决了。
运行`build.cmd`后会显示各种编程语言的名字。感谢您的开源！
